aliases:
  - &save-cache-yarn
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - ./node_modules
  - &restore-cache-yarn
    name: Restore Yarn Package Cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}

defaults: &defaults
  working_directory: ~/ios-simulator-app-exporter
  docker:
    - image: circleci/node:10

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run:
          name: Yarn version
          command: yarn -v
      - run:
          name: Yarn Install
          command: |
            yarn install --frozen-lockfile --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save_cache: *save-cache-yarn
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ios-simulator-app-exporter
      - run:
          name: Run test
          command: yarn test
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ios-simulator-app-exporter
      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  tests:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
